using System.ComponentModel.DataAnnotations;

using Marten;

using Microsoft.AspNetCore.Mvc;

using Wolverine.Http;
using Wolverine.Marten;

namespace Api.UseCases.Mitarbeiter.NameÄndern;

// Inspect the code generated by Wolverine for this handler:
//
// dotnet run --project Api/Api.csproj -- codegen write
public static class NameÄndernEndpoint
{
  public record NameÄndernRequest(string Name);

  // https://wolverine.netlify.app/guide/http/problemdetails.html
  public static ProblemDetails Before(NameÄndernRequest request)
  {
    // Validate the request, e.g. name must not be null or empty.
    if (string.IsNullOrEmpty(request.Name))
    {
      return new ProblemDetails
      {
        Detail = "Name must not be empty",
        Status = 400,
      };
    }

    return WolverineContinue.NoProblems;
  }

  // https://wolverine.netlify.app/guide/http/middleware.html#required-inputs
  public static Task<Mitarbeiter?> LoadAsync(string id,
                                             IDocumentSession session)
    => session.LoadAsync<Mitarbeiter>(id);

  [Tags("Mitarbeiter")]
  [WolverinePatch("/mitarbeiter/{id}/name")]

  // If the "id" parameter is removed here, LoadAsync above would receive
  // the HttpContext.TraceIdentifier as its "id" parameter value.
  // https://github.com/JasperFx/wolverine/issues/608
  public static StoreDoc<Mitarbeiter> Handle(string id,
                                             NameÄndernRequest request,
                                             [Required] Mitarbeiter mitarbeiter)
  {
    var kopie = mitarbeiter with { Name = request.Name };

    return MartenOps.Store(kopie);
  }
}
